# Datasource
spring:
 datasource:
  url: jdbc:postgresql://192.168.99.100:5432/employer
  username: admin
  password: secret
 jpa:
  hibernate:
   ddl-auto: update

server:
 port: 9595

spring.jackson.deserialization.fail-on-unknown-properties: true

jwt.secret: fsdfsdfsdf

security.ignored: /authenticate

#Log http requests and responses
logging.level.org.springframework.ws.server.MessageTracing.sent: TRACE
